### ISSUE TITLE
Update Loser Simulator to conform to Google Play's required Android SDK's

### ISSUE THREAD

**Issue by DivergentEuropeans** [DivergentEuropeans/loser-simulator#10]
LS1 was kicked off Google Play due to getting out of date. So update LS1 to conform to Google Play's required Android SDK's

**Comment by Priyansh61** [comment]
@DivergentEuropeans The `compileSDK` is already set to 33, which is compativble to Google Play requirement.

```
New apps must target Android 13 (API level 33) or higher; except for [Wear OS](https://developer.android.com/wear) apps, which must target a version between Android 11 (API level 30) and Android 13 (API level 33), inclusive.

App updates must target Android 13 or higher and adjust for behavioral changes in Android 13; except for Wear OS apps, which must target Android 11.
```

Still I am thinking of thinking of upgrading to 34 for precautionary measure.

**Comment by DivergentEuropeans** [comment]
This was solved by @Priyansh61 and I. I have recovered my key for LS1, updated various details w/ Google to regain access, and LS1 is now back on Google Play so we can close this out.
