### ISSUE TITLE
Fix start-up, run-time crashes/bugs

### ISSUE THREAD

**Issue by DivergentEuropeans** [DivergentEuropeans/loser-simulator#9]
Sometimes, when we open LS2 from scratch, it crashes. This seems to be relate to the way the FragmentManager processes, stops processing, and checks for if previously fragments are being processed or were processed

**Comment by Priyansh61** [comment]
Let me sideload the app with new changes on my android and use it to find out why it actually crashes since I am not able to recreate the crash on the Virtual device.

**Comment by DivergentEuropeans** [comment]
I think I have fixed this now @Priyansh61
